// <auto-generated />
namespace AirOut.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddTestMVC_CRUD : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddTestMVC_CRUD));
        
        string IMigrationMetadata.Id
        {
            get { return "201906020631118_AddTestMVC_CRUD"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
